name: MobileCI
on: [ push ]

job:

  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run tests
        run: ./gradlew test
